name: pr

on:
  pull_request:
    branches: [main]
jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 22.20.0
      - name: Clone
        uses: actions/checkout@v2
      - name: Install dependencies
        run: 'yarn install --frozen-lockfile'
      - name: Lint
        run: yarn lint